// `sm install-hook` 와 hook 이 호출하는 `sm hook-run` 핸들러.
// hook 파일 자체는 짧게 → 실제 로직은 여기 TS 에 두어 디버깅/수정 쉬움.
//
// 이 모듈은 두 가지 설치 모드를 제공한다.
//   1) 프로젝트 단위: 현재 프로젝트의 .git/hooks/prepare-commit-msg 에 설치
//   2) 글로벌 단위 : ~/.smart-msg/hooks/prepare-commit-msg 에 설치하고
//                  git config --global core.hooksPath 로 모든 git 저장소가
//                  이 폴더의 hook 을 사용하도록 한다 (한 번만 설정하면 끝).
import { existsSync } from "node:fs";
import { writeFile, readFile, chmod, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import prompts from "prompts";
import { execa } from "execa";
import { loadConfig, updateConfig, getConfigDir } from "./config.js";
import { getStagedDiff } from "./git.js";
import { generateCommitMessage } from "./ai.js";

const HOOK_NAME = "prepare-commit-msg";
// hook 파일 안에 이 마커가 있으면 "우리가 깐 hook" 으로 식별 → 안전한 재설치/제거 가능.
const HOOK_MARKER = "# smart-msg-managed";

// 실제 hook 셸 스크립트. 단순히 우리 CLI 호출만. Windows 는 git-bash 가 sh 실행해줌.
const HOOK_SCRIPT = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by smart-msg. Do not edit by hand.
# 인자: $1 = 메시지 파일, $2 = source (message/merge/squash/commit/template/없음)
exec sm hook-run "$1" "$2"
`;

// 글로벌 hook 폴더 위치. ~/.smart-msg/hooks 에 두어 config 와 같은 곳에서 관리한다.
function getGlobalHooksDir(): string {
  return join(getConfigDir(), "hooks");
}

// `sm install-hook` 명령 본체. 프로젝트 단위 설치를 수행한다.
export async function runInstallHook(): Promise<void> {
  const cwd = process.cwd();
  const gitDir = join(cwd, ".git");

  // 1) 현재 폴더가 git repo 인지 확인. 아니면 일찍 종료.
  if (!existsSync(gitDir)) {
    console.error("git 저장소가 아닙니다. 프로젝트 루트에서 실행하시기 바랍니다.");
    process.exit(1);
  }

  const hooksDir = join(gitDir, "hooks");
  if (!existsSync(hooksDir)) {
    await mkdir(hooksDir, { recursive: true });
  }

  const hookPath = join(hooksDir, HOOK_NAME);

  // 2) 기존 hook 처리. 우리 게 이미 있으면 skip, 남의 게 있으면 백업 후 덮어쓰기 (사용자 confirm).
  if (existsSync(hookPath)) {
    const existing = await readFile(hookPath, "utf-8");
    if (existing.includes(HOOK_MARKER)) {
      console.log("이미 smart-msg hook 이 설치되어 있습니다.");
      await rememberHook(hookPath);
      return;
    }
    const { ok } = await prompts({
      type: "confirm",
      name: "ok",
      message: `기존 ${HOOK_NAME} hook 이 존재합니다. 백업(.bak) 후 덮어쓰시겠습니까?`,
      initial: false,
    });
    if (!ok) {
      console.log("취소되었습니다.");
      return;
    }
    await writeFile(`${hookPath}.bak`, existing, "utf-8");
    console.log(`기존 hook 을 백업하였습니다: ${hookPath}.bak`);
  }

  // 3) hook 파일 쓰기 + 실행 권한.
  await writeFile(hookPath, HOOK_SCRIPT, "utf-8");
  try {
    await chmod(hookPath, 0o755);
  } catch {
    // Windows 등 권한 모델이 다른 경우 무시한다.
  }

  // 4) config 에 경로 기록 → 나중에 `sm uninstall` 이 자동 정리 가능.
  await rememberHook(hookPath);

  console.log(`설치가 완료되었습니다: ${hookPath}`);
}

// hook 경로를 config 에 누적 기록. 중복 방지 + uninstall 시 일괄 정리용.
async function rememberHook(hookPath: string): Promise<void> {
  const cfg = await loadConfig();
  const hooks = cfg?.installedHooks ?? [];
  if (!hooks.includes(hookPath)) {
    hooks.push(hookPath);
    await updateConfig({ installedHooks: hooks });
  }
}

// 글로벌 hook 설치. 사용자의 모든 git 저장소에서 자동으로 동작한다.
// 핵심 동작:
//   1) ~/.smart-msg/hooks/prepare-commit-msg 파일 작성
//   2) git config --global core.hooksPath ~/.smart-msg/hooks 설정
// 이로써 사용자는 매 프로젝트마다 install-hook 을 수동으로 실행할 필요가 없다.
export async function runInstallHookGlobal(): Promise<boolean> {
  const hooksDir = getGlobalHooksDir();
  const hookPath = join(hooksDir, HOOK_NAME);

  // 1) 기존에 설정된 core.hooksPath 가 있으면 사용자에게 알려주고 동의를 받는다.
  //    husky 같은 도구를 이미 쓰고 있을 가능성이 있으므로 무단 덮어쓰기는 하지 않는다.
  let existingHooksPath = "";
  try {
    const { stdout } = await execa("git", [
      "config",
      "--global",
      "--get",
      "core.hooksPath",
    ]);
    existingHooksPath = stdout.trim();
  } catch {
    // 설정 안 되어 있는 경우 git 이 비정상 종료 코드를 반환하지만 정상 흐름이다.
  }

  if (existingHooksPath && existingHooksPath !== hooksDir) {
    console.log("");
    console.log(`현재 git 글로벌 core.hooksPath 가 다음 값으로 설정되어 있습니다:`);
    console.log(`  ${existingHooksPath}`);
    console.log("");
    console.log("이 값을 smart-msg 의 hook 폴더로 변경하면 기존 hook 도구(husky 등)가 동작하지 않을 수 있습니다.");
    const { override } = await prompts({
      type: "confirm",
      name: "override",
      message: "기존 설정을 덮어쓰고 smart-msg 글로벌 hook 을 사용하시겠습니까?",
      initial: false,
    });
    if (!override) {
      console.log("글로벌 hook 설치를 건너뛰었습니다. 프로젝트 단위 설치만 진행합니다.");
      return false;
    }
    // 기존 값을 config 에 보존 → uninstall 시 복원할 수 있도록.
    await updateConfig({ previousGlobalHooksPath: existingHooksPath });
  }

  // 2) hook 폴더 및 파일 생성.
  if (!existsSync(hooksDir)) {
    await mkdir(hooksDir, { recursive: true });
  }
  await writeFile(hookPath, HOOK_SCRIPT, "utf-8");
  try {
    await chmod(hookPath, 0o755);
  } catch {
    // Windows 권한 모델 차이 무시.
  }

  // 3) git 글로벌 설정 적용.
  await execa("git", ["config", "--global", "core.hooksPath", hooksDir]);

  // 4) config 에 표식 저장 → uninstall 시 인식 가능.
  await updateConfig({ globalHookInstalled: true });

  return true;
}

// hook 이 호출하는 숨은 명령. 사용자가 직접 부르는 게 아니다.
// 안전 규칙을 어기면 사용자 워크플로우가 깨지므로 보수적으로 동작한다.
export async function runHookHandler(
  msgFile: string,
  source?: string
): Promise<void> {
  // 1) source 가 명시적으로 있으면 (사용자가 -m 줬거나 merge/squash/amend 등) 손대지 않음.
  //    "template" 만 우리가 채울 가치가 있는 케이스.
  if (source && source !== "template") return;

  // 2) 메시지 파일에 이미 의미있는 내용이 있으면 (코멘트 # 제외) 손대지 않음.
  //    git commit 템플릿이나 다른 hook 이 먼저 채운 경우 보호.
  let existing = "";
  try {
    existing = await readFile(msgFile, "utf-8");
  } catch {
    return;
  }
  const meaningful = existing
    .split("\n")
    .filter((l) => !l.trim().startsWith("#") && l.trim().length > 0)
    .join("\n")
    .trim();
  if (meaningful) return;

  // 3) staged diff 없으면 굳이 AI 호출하지 않는다.
  const diff = await getStagedDiff();
  if (!diff.trim()) return;

  // 4) AI 호출. 실패해도 commit 자체는 진행되어야 한다.
  try {
    const message = await generateCommitMessage(diff);
    await writeFile(msgFile, `${message}\n\n${existing}`, "utf-8");
  } catch (e) {
    console.error(`[sm hook] ${(e as Error).message}`);
  }
}
