// `sm install-hook` 와 hook 이 호출하는 `sm hook-run` 핸들러.
// hook 파일 자체는 짧게 → 실제 로직은 여기 TS 에 두어 디버깅/수정 쉬움.
import { existsSync } from "node:fs";
import { writeFile, readFile, chmod, mkdir } from "node:fs/promises";
import { join } from "node:path";
import prompts from "prompts";
import { loadConfig, updateConfig } from "./config.js";
import { getStagedDiff } from "./git.js";
import { generateCommitMessage } from "./ai.js";

const HOOK_NAME = "prepare-commit-msg";
// hook 파일 안에 이 마커가 있으면 "우리가 깐 hook" 으로 식별 → 안전한 재설치/제거 가능.
const HOOK_MARKER = "# smart-msg-managed";

// 실제 hook 셸 스크립트. 단순히 우리 CLI 호출만. Windows 는 git-bash 가 sh 실행해줌.
const HOOK_SCRIPT = `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by 'sm install-hook'. Do not edit by hand.
# 인자: $1 = 메시지 파일, $2 = source (message/merge/squash/commit/template/없음)
exec sm hook-run "$1" "$2"
`;

// `sm install-hook` 명령 본체.
export async function runInstallHook(): Promise<void> {
  const cwd = process.cwd();
  const gitDir = join(cwd, ".git");

  // 1) 현재 폴더가 git repo 인지 확인. 아니면 일찍 종료.
  if (!existsSync(gitDir)) {
    console.error("git 저장소가 아닙니다. 프로젝트 루트에서 실행하시기 바랍니다.");
    process.exit(1);
  }

  const hooksDir = join(gitDir, "hooks");
  if (!existsSync(hooksDir)) {
    await mkdir(hooksDir, { recursive: true });
  }

  const hookPath = join(hooksDir, HOOK_NAME);

  // 2) 기존 hook 처리. 우리 게 이미 있으면 skip, 남의 게 있으면 백업 후 덮어쓰기 (사용자 confirm).
  if (existsSync(hookPath)) {
    const existing = await readFile(hookPath, "utf-8");
    if (existing.includes(HOOK_MARKER)) {
      console.log("이미 smart-msg hook 이 설치되어 있습니다.");
      await rememberHook(hookPath);
      return;
    }
    const { ok } = await prompts({
      type: "confirm",
      name: "ok",
      message: `기존 ${HOOK_NAME} hook 이 존재합니다. 백업(.bak) 후 덮어쓰시겠습니까?`,
      initial: false,
    });
    if (!ok) {
      console.log("취소되었습니다.");
      return;
    }
    await writeFile(`${hookPath}.bak`, existing, "utf-8");
    console.log(`기존 hook 을 백업하였습니다: ${hookPath}.bak`);
  }

  // 3) hook 파일 쓰기 + 실행 권한. Windows 에선 chmod 가 사실상 무시됨.
  await writeFile(hookPath, HOOK_SCRIPT, "utf-8");
  try {
    await chmod(hookPath, 0o755);
  } catch {
    // Windows 등 권한 모델이 다른 경우 무시. git for windows 는 그래도 sh 로 잘 실행함.
  }

  // 4) config 에 경로 기록 → 나중에 `sm uninstall` 이 자동 정리 가능.
  await rememberHook(hookPath);

  console.log(`설치가 완료되었습니다: ${hookPath}`);
  console.log(
    "이후 'git commit' 명령 또는 IntelliJ 커밋 창에서 메시지가 자동으로 채워집니다."
  );
  console.log("'git commit -m \"...\"' 형식으로 메시지를 직접 지정하는 경우 hook 은 동작하지 않습니다.");
}

// hook 경로를 config 에 누적 기록. 중복 방지 + uninstall 시 일괄 정리용.
async function rememberHook(hookPath: string): Promise<void> {
  const cfg = await loadConfig();
  const hooks = cfg?.installedHooks ?? [];
  if (!hooks.includes(hookPath)) {
    hooks.push(hookPath);
    await updateConfig({ installedHooks: hooks });
  }
}

// hook 이 호출하는 숨은 명령. 사용자가 직접 부르는 게 아님.
// 안전 규칙을 어기면 사용자 워크플로우가 깨지니까 보수적으로 동작.
export async function runHookHandler(
  msgFile: string,
  source?: string
): Promise<void> {
  // 1) source 가 명시적으로 있으면 (사용자가 -m 줬거나 merge/squash/amend 등) 손대지 않음.
  //    "template" 만 우리가 채울 가치가 있는 케이스.
  if (source && source !== "template") return;

  // 2) 메시지 파일에 이미 의미있는 내용이 있으면 (코멘트 # 제외) 손대지 않음.
  //    git commit 템플릿이나 다른 hook 이 먼저 채운 경우 보호.
  let existing = "";
  try {
    existing = await readFile(msgFile, "utf-8");
  } catch {
    return; // 파일 못 읽으면 그냥 비켜섬 — 절대 commit 자체를 막지 말 것.
  }
  const meaningful = existing
    .split("\n")
    .filter((l) => !l.trim().startsWith("#") && l.trim().length > 0)
    .join("\n")
    .trim();
  if (meaningful) return;

  // 3) staged diff 없으면 어차피 git 이 거부할 거라 굳이 AI 호출 안 함 → 토큰 낭비 방지.
  const diff = await getStagedDiff();
  if (!diff.trim()) return;

  // 4) AI 호출. 실패하면 조용히 비켜섬 → commit 자체는 진행되어야 함.
  try {
    const message = await generateCommitMessage(diff);
    // 기존 코멘트 라인 보존 (git 안내문, 변경 파일 목록 등) + 위에 우리 메시지 삽입.
    await writeFile(msgFile, `${message}\n\n${existing}`, "utf-8");
  } catch (e) {
    // hook 에서 commit 막으면 사용자 경험 최악 → stderr 알림만 하고 종료 코드 0.
    console.error(`[sm hook] ${(e as Error).message}`);
  }
}
